name: CI

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: deps
        run: sudo bash linux-deps.sh
      - name: build 
        run: sudo bash build.sh
      - name: test
        run: ./fgl ./tests/test.fgl
