name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - "!master"
    paths:
    - 'Dockerfile'
    - '.dockerignore'
    - '.github/workflows/docker-publish.yml'
jobs:
    push_to_registries:
        runs-on: ubuntu-latest
        env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
            FORCE_COLOR: 1
        permissions:
            packages: write
            contents: read
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2.4.2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Docker Hub
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Log in to the Container registry
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.CONTAINER_PUBLISH }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta2
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: |
                    fgygh/fglanguage
                    ghcr.io/${{ github.repository }}
                tags: latest
            - name: Build and push Docker images
              uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
              with:
                context: .
                push: true
                tags: ${{ steps.meta2.outputs.tags }}
                labels: ${{ steps.meta2.outputs.labels }}
                uses: actions/checkout@v2
